CHANGELOG.rst, README.rst, docs/conf.py
* The package name has changed to `cirq-iqm`, so we also reset the version history.
* CHANGELOG items should from now on have links to pull requests that implement the feature or fix the bug, done using a `sphinx.ext.extlinks` RST role.
=> Reset version to 0.1

CHANGELOG.rst, src/cirq_iqm/adonis.py, src/cirq_iqm/iqm_device.py, tests/adonis_test.py, tests/iqm_gates_test.py
* Adonis gateset update: CZ is the only native two-qubit gate for now.
* Added decompositions targeting CZ.
* Cleaning up type annotations.
=> Adonis gateset updated. CZ-targeting decompositions added.

CHANGELOG.rst
* Makes the changelog [render nicely in Github web UI](https://github.com/iqm-finland/cirq-on-iqm/blob/changelog-links/CHANGELOG.rst)
* Makes the links followable when [viewing the file e.g. in a text editor](https://raw.githubusercontent.com/iqm-finland/cirq-on-iqm/changelog-links/CHANGELOG.rst)
=> Switch to self-sufficient links

README.rst, src/cirq_iqm/adonis.py, src/cirq_iqm/iqm_device.py, src/cirq_iqm/iqm_operation_mapping.py, src/cirq_iqm/iqm_remote.py, src/cirq_iqm/valkmusa.py, tests/adonis_test.py, tests/iqm_operation_mapping_test.py, tests/iqm_remote_test.py, tests/settings.json, tests/test_qubit_mapping.py, tests/valkmusa_test.py
- Remove `IQMQubit` class and use `cirq.NameQubit` instead
- Automatically generate identity qubit mapping (using device qubit names) when not provided by the end user
- Add relevant tests
COMP-118
=> enhance the handling of qubit_mapping

tests/conftest.py
Error was due to pylint being updated to version 2.10. which added a check for this.
=> Add explicit encoding to open call to fix linter error.

CHANGELOG.rst, examples/demo_common.py, src/cirq_iqm/adonis.py, src/cirq_iqm/iqm_device.py, src/cirq_iqm/valkmusa.py, tests/test_adonis.py, tests/test_optimization.py
* `Adonis` native gate set updated. Rz is no longer considered native.
* `DropRZBeforeMeasurement` can now also drop final Rz gates if required.
* Bugfix: `DropRZBeforeMeasurement` sometimes did not drop gates it should have.
* Bugfix: The demos did not actually use the simplified circuits.
* Some cleanup.
COMP-160
=> Fix various Rz issues.

tests/test_adonis.py, tests/test_valkmusa.py
pylint version `2.11.*` was released overnight, and the linting job is failing with 
```
Formatting a regular string which could be a f-string (consider-using-f-string)
```
Updated the failing lines to comply with the new pylint version.
P.S.
The relevant line from pylint changelog:
```
Added consider-using-f-string: Emitted when .format() or '%' is being used to format a string.
Closes #3592
```
=> Fix linting issues

CHANGELOG.rst
Update for 2.0. #45 is a breaking change.
=> Update for release 2.0

setup.cfg, tox.ini
* Fix typo in `iqm-client` dependency, bump version to 1.4
* Bump `build` version to 0.7.0
=> Fix iqm-client dependency, bump build to 0.7.0

.github/workflows/publish.yml, .github/workflows/tag_and_release.yml
When the publish workflow is triggered from another workflow it will fail unless necessary secrets as passed to it from the caller workflow. This PR adds these secrets to the workflow call.
COMP-212
=> Pass secrets to the workflow call

.github/workflows/publish.yml
In order to get clean release number, the docs must be built on a tagged commit.
Add checkout step to `publish_docs` job to get to the last tagged commit.
Tags are available only if `actions/checkout@v2` fetches the full history.
For that to happen it needs parameter `fetch-depth: 0`.
=> Checkout last tagged commit in publish workflow

setup.cfg, src/cirq_iqm/iqm_sampler.py
The latest minor release (0.14.0) of Cirq, released yesterday, is not backwards compatible with the previous version 0.13.1. Now the `cirq.study.Result` class is abstract and cannot be instantiated. This PR upgrades the Cirq dependency.
=> Bump Cirq dependency

CHANGELOG.rst, docs/user_guide.rst, examples/usage.ipynb, src/cirq_iqm/iqm_sampler.py, src/cirq_iqm/optimizers.py, tests/test_adonis.py, tests/test_iqm_sampler.py, tests/test_optimization.py
It won't be possible to attach devices to circuits in Cirq 0.15. This updates circuit execution tests and IQM sampler accordingly.
=> Update tests, sampler for cirq 0.15 deprecations

AUTHORS.rst, CHANGELOG.rst, README.rst, examples/demo_apollo.py, examples/usage.ipynb, src/cirq_iqm/devices/__init__.py, src/cirq_iqm/devices/adonis.py, src/cirq_iqm/devices/apollo.py, src/cirq_iqm/devices/iqm_device.py, src/cirq_iqm/devices/valkmusa.py, tests/test_apollo.py, tests/test_iqm_device.py
Support for 20-qubit IQM Apollo architecture.
The Apollo device differs from Adonis only in two aspects: number of qubits and the connectivity of qubits. The native gates are the same in both Apollo and Adonis, so decomposition logic is also the same.
=> Apollo 20-qubit architecture support

CHANGELOG.rst, docs/user_guide.rst, setup.cfg, src/cirq_iqm/iqm_sampler.py, tests/test_iqm_sampler.py
[IQM Client 6.1](https://github.com/iqm-finland/iqm-client/commit/45654f63d3f363f2996d143f145a38cd19785b35) now allows to specify a `calibration_set_id`. This PR updates Cirq-on-IQM accordingly.
=> Add optional calibration_set_id to IQMSampler

CHANGELOG.rst, docs/user_guide.rst, examples/usage.ipynb, setup.cfg, src/cirq_iqm/devices/__init__.py, src/cirq_iqm/devices/adonis.py, src/cirq_iqm/devices/apollo.py, src/cirq_iqm/devices/iqm_device.py, src/cirq_iqm/devices/iqm_device_metadata.py, src/cirq_iqm/devices/valkmusa.py, src/cirq_iqm/iqm_sampler.py, tests/test_adonis.py, tests/test_apollo.py, tests/test_iqm_device.py, tests/test_iqm_device_metadata.py, tests/test_iqm_sampler.py, tests/test_valkmusa.py
* Qubit connectivity and native gateset of a device are now defined using DeviceMetadata instead of class attributes, to have an interface consistent with other cirq* devices.
* IQMSampler will now by default use quantum architecture obtained from IQMClient to build the device metadata
=> Implement metadata for IQM devices

CHANGELOG.rst, setup.cfg
The new version of sphinx-multiversion is not using symlinks approach for reducing docs size, which was incompatible with GitHub Actions.
=> Fix multi version docs publication

docs/user_guide.rst
https://quantumai.google/reference/python/cirq/HardCodedInitialMapper
`initial_mapper = cirq.cirq.HardCodedInitialMapper({q1: adonis.qubits[2], q2: adonis.qubits[0]})` 
Should be 
`initial_mapper = cirq.HardCodedInitialMapper({q1: adonis.qubits[2], q2: adonis.qubits[0]})`
=> Correct HardCodedInitialMapper usage in docs

CHANGELOG.rst, pyproject.toml, src/cirq_iqm/iqm_sampler.py, tests/test_iqm_sampler.py
If the user interrupts the program with ctrl-c or similar (which creates a KeyboardInterrupt) when a job has been submitted to the server and the client is waiting for results, the submitted job is aborted.
=> Add ability to abort submitted jobs

CHANGELOG.rst, docs/user_guide.rst
Hi, I would like to add 2 examples to the cirq-on-iqm docs: 
1. Batch submission with `IQMSampler.run_iqm_batch`
2. Parameterized submission using ` cirq.Linspace` + `IQMSampler.run_sweep`
I can also add these examples to the `examples` directory. 
I noticed that the documentation is somewhat formatted, however tox/black does not auto format it. Please also comment on the line lengths and how previous authors have kept it consistent. 
I would also like to add a table similar to https://iqm-finland.github.io/qiskit-on-iqm/user_guide.html#running-a-quantum-circuit-on-an-iqm-quantum-computer showing the different backend options. Why were these previously not added? They could be added for example under `Running on a real quantum computer`. 
Thanks!
=> Add Advanced examples to Documentation 

README.rst
PyPI does not allow Sphinx role :file: and rejects publishing attempt of the package
=> Remove Sphinx role :file:

tests/test_optimization.py
There has been a recent regression in astroid module (since version 3.2.0, most likely related to changes in igetattr method). It causes our CI workflows runs to fail, because pylint fails to infer the correct type of some variables.
astroid is a transitive dependency (pytest-pylint <- pylint <- astroid). Versions of transitive dependencies are not pinned in the project configuration, which allowed astroid regression to break the CI.
pylint checks should be re-enabled once astroid bug https://github.com/pylint-dev/astroid/issues/2448 gets fixed.
=> Disable failing pylint checks

CHANGELOG.rst, docs/user_guide.rst, pyproject.toml, src/iqm/cirq_iqm/__init__.py, src/iqm/cirq_iqm/devices/iqm_device.py, src/iqm/cirq_iqm/devices/iqm_device_metadata.py, src/iqm/cirq_iqm/devices/valkmusa.py, src/iqm/cirq_iqm/iqm_gates.py, src/iqm/cirq_iqm/iqm_operation_mapping.py, src/iqm/cirq_iqm/iqm_sampler.py, src/iqm/cirq_iqm/serialize.py, src/iqm/cirq_iqm/transpiler.py, tests/conftest.py, tests/test_adonis.py, tests/test_apollo.py, tests/test_iqm_device.py, tests/test_iqm_operation_mapping.py, tests/test_iqm_sampler.py
Added naive MOVE gate insertion support for use of Deneb with Cirq. 
The tests can only pass after https://github.com/iqm-finland/iqm-client/pull/124 has been merged.
=> Added Deneb-style transpiling support (requires iqm-client 18.0)

CHANGELOG.rst, docs/conf.py, docs/user_guide.rst, examples/demo_adonis.py, examples/demo_common.py, src/iqm/cirq_iqm/devices/iqm_device.py, src/iqm/cirq_iqm/devices/iqm_device_metadata.py, src/iqm/cirq_iqm/iqm_sampler.py, tests/test_adonis.py, tests/test_apollo.py
* Routing method now returns a tuple, example code was not updated to reflect this. Now fixed.
* Remove validation check and routing quirks that prevent mid-circuit measurements.
* Update docs.
COMP-1490
=> Fix example code, enable mid-circuit measurements.

src/iqm/cirq_iqm/devices/iqm_device_metadata.py, tests/test_iqm_sampler.py
Recently released pylint v3.3.0 introduces new check of "too-many-positional-arguments". This makes the CI checks to fail. This PR changes method signature to comply with pylint recommendations.
Why did CI started failing all of a sudden? pylint version of the project is not pinned, only pytest-pylint is pinned to v0.21.0. pytest-pylint requires pylint as [requires: pylint>=2.15.0]. That's why the new version of pylint was installed by CI.
```
$ pipdeptree --reverse --packages pylint
------------------------------------------------------------------------
pylint==3.3.0
└── pytest-pylint==0.21.0 [requires: pylint>=2.15.0]
```
=> Fix Failing CI Checks

.github/workflows/publish.yml, CHANGELOG.rst
Does the same thing as https://github.com/iqm-finland/iqm-client/pull/133.
Here I didn't add documentation about the alternative `git clone` options, because the repository size is not as big as iqm-client (~50MB vs ~500MB), so it's still pretty fast to clone normally.
=> Remove unnecessary build files when publishing documentation

.github/workflows/publish.yml, AUTHORS.rst, CHANGELOG.rst, docs/user_guide.rst, pyproject.toml, src/iqm/cirq_iqm/devices/iqm_device.py, src/iqm/cirq_iqm/devices/iqm_device_metadata.py, src/iqm/cirq_iqm/iqm_operation_mapping.py, src/iqm/cirq_iqm/iqm_sampler.py, src/iqm/cirq_iqm/optimizers.py, src/iqm/cirq_iqm/transpiler.py, tests/conftest.py, tests/test_iqm_device.py, tests/test_iqm_device_metadata.py, tests/test_iqm_operation_mapping.py, tests/test_iqm_sampler.py, tests/test_optimization.py
- IQMDeviceMetadata can now be created from a DQA, and creating it from QuantumArchitectureSpecification (static architecture) is no longer supported.
- IQMDevice/IQMDeviceMetadata can still be created independently of the architecture/calset, so the hardcoded Adonis, Apollo etc. classes are not removed. They are currently used mainly for tests, and could be used for simulation.
- IQMSampler uses the specified calset (or server default calset if `calibration_set_id` not specified) to create the IQMDeviceMetadata/IQMDevice.
-  IQMSampler adds the calset id to the circuits it decomposes/routes. The calset id is used to warn the user of mismatches between the calset used for execution and the decomposed/routed circuits.
- Requires https://github.com/iqm-finland/iqm-client/pull/140 to be …
=> Use dynamic quantum architecture (DQA) for circuit decomposition/routing

CHANGELOG.rst, docs/user_guide.rst, src/iqm/cirq_iqm/iqm_sampler.py
This pull request updates the authentication process in IQMProvider and improves the user guide to better reflect the usage of IQM Resonance.
Changes:
* Updated IQMSampler to mention authentication option for IQM Resonance
* Mentioned the support for the token parameter in the User guide.
* Added separating headlines for IQM Resonance and on-prem QCs
=> Reflect Resonance authentication better in documentation

examples/demo_iqm_execution.py
Currently, the example proposes to first run `decompose_circuit` followed by a `route_circuit`.
However, if the routing needs to introduce swap gates, these will stay in the circuit until execution where they lead to an error:
```
OperationNotSupportedError: <class 'cirq.ops.swap_gates.SwapPowGate'> not natively supported.
```
Therefore, the order of these two operations needs to be reversed.
=> switch order of route and decompose
